import '../services/auth_repository.dart';

/// Represents a program or event that a learner can browse, register for,
/// and leave feedback on.
class Program {
  final String id;
  final String title;
  final String category;
  final String description;
  final DateTime date;
  final String location;
  final int seatsAvailable;
  final bool isRegistered;

  const Program({
    required this.id,
    required this.title,
    required this.category,
    required this.description,
    required this.date,
    required this.location,
    required this.seatsAvailable,
    this.isRegistered = false,
  });

  Program copyWith({bool? isRegistered}) {
    return Program(
      id: id,
      title: title,
      category: category,
      description: description,
      date: date,
      location: location,
      seatsAvailable: seatsAvailable,
      isRegistered: isRegistered ?? this.isRegistered,
    );
  }
}

/// A very small in-memory data source standing in for a future backend
/// (e.g. Firebase / REST API). Swapping this out is the main integration
/// point for Week 2+ work.
class ProgramRepository {
  static final List<Program> _programs = [
    // Bootcamp
    Program(
      id: 'p1',
      title: 'Career Readiness Bootcamp',
      category: 'Bootcamp',
      description:
          'Resume reviews, mock interviews, and networking practice with '
          'industry mentors.',
      date: DateTime.now().add(const Duration(days: 7)),
      location: 'Excelerate Hub — Room 204',
      seatsAvailable: 12,
    ),
    Program(
      id: 'p2',
      title: 'AI for Beginners Bootcamp',
      category: 'Bootcamp',
      description: 'Explore generative AI, prompt design, and real-world use cases.',
      date: DateTime.now().add(const Duration(days: 4)),
      location: 'Innovation Lab — Room 3',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p3',
      title: 'Cloud Computing Foundations',
      category: 'Bootcamp',
      description: 'A structured track covering cloud basics, services, and deployment.',
      date: DateTime.now().add(const Duration(days: 21)),
      location: 'Tech Center — Floor 2',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p4',
      title: 'Product Management Bootcamp',
      category: 'Bootcamp',
      description: 'Build product roadmaps, user stories, and go-to-market strategies.',
      date: DateTime.now().add(const Duration(days: 9)),
      location: 'Online — Zoom',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p5',
      title: 'Full-Stack Development Bootcamp',
      category: 'Bootcamp',
      description: 'Hands-on web app development with frontend and backend tooling.',
      date: DateTime.now().add(const Duration(days: 11)),
      location: 'Coding Studio — Room 5',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p6',
      title: 'Leadership Bootcamp',
      category: 'Bootcamp',
      description: 'Develop leadership habits, team coaching, and influence skills.',
      date: DateTime.now().add(const Duration(days: 13)),
      location: 'Excelerate Hub — Room 101',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p7',
      title: 'Finance Fundamentals Bootcamp',
      category: 'Bootcamp',
      description: 'Understand budgeting, cash flow, financial models and investor metrics.',
      date: DateTime.now().add(const Duration(days: 15)),
      location: 'Online — Google Meet',
      seatsAvailable: 25,
    ),
    Program(
      id: 'p8',
      title: 'Digital Marketing Bootcamp',
      category: 'Bootcamp',
      description: 'Launch campaigns, measure ROI, and learn growth marketing tools.',
      date: DateTime.now().add(const Duration(days: 17)),
      location: 'Marketing Lab',
      seatsAvailable: 24,
    ),
    Program(
      id: 'p9',
      title: 'Entrepreneurship Bootcamp',
      category: 'Bootcamp',
      description: 'Validate ideas, pitch investors, and prepare a business plan.',
      date: DateTime.now().add(const Duration(days: 19)),
      location: 'Startup Studio',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p10',
      title: 'Data Science Bootcamp',
      category: 'Bootcamp',
      description: 'Learn analytics, machine learning, and practical data projects.',
      date: DateTime.now().add(const Duration(days: 23)),
      location: 'Data Lab — Room 2',
      seatsAvailable: 20,
    ),
    // Seminar
    Program(
      id: 'p11',
      title: 'Cybersecurity Essentials Seminar',
      category: 'Seminar',
      description: 'A beginner-friendly look at digital safety, phishing, and privacy.',
      date: DateTime.now().add(const Duration(days: 12)),
      location: 'Online — Teams',
      seatsAvailable: 40,
    ),
    Program(
      id: 'p12',
      title: 'Sustainable Business Seminar',
      category: 'Seminar',
      description: 'Learn sustainable strategy, ESG reporting, and green operations.',
      date: DateTime.now().add(const Duration(days: 5)),
      location: 'Eco Center',
      seatsAvailable: 35,
    ),
    Program(
      id: 'p13',
      title: 'Personal Finance Seminar',
      category: 'Seminar',
      description: 'Master budgeting, saving, credit scores, and debt management.',
      date: DateTime.now().add(const Duration(days: 8)),
      location: 'Finance Studio',
      seatsAvailable: 30,
    ),
    Program(
      id: 'p14',
      title: 'Startup Fundraising Seminar',
      category: 'Seminar',
      description: 'Understand term sheets, valuations, and investor slides.',
      date: DateTime.now().add(const Duration(days: 10)),
      location: 'Pitch Room',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p15',
      title: 'Remote Work Seminar',
      category: 'Seminar',
      description: 'Best practices for productivity, team culture, and virtual leadership.',
      date: DateTime.now().add(const Duration(days: 14)),
      location: 'Online — Zoom',
      seatsAvailable: 45,
    ),
    Program(
      id: 'p16',
      title: 'AI Ethics Seminar',
      category: 'Seminar',
      description: 'Explore responsible AI, bias, privacy, and governance.',
      date: DateTime.now().add(const Duration(days: 18)),
      location: 'Meetup Hall',
      seatsAvailable: 28,
    ),
    Program(
      id: 'p17',
      title: 'Career Transition Seminar',
      category: 'Seminar',
      description: 'Plan career shifts, resume pivots, and credential mapping.',
      date: DateTime.now().add(const Duration(days: 20)),
      location: 'Excelerate Hub — Room 110',
      seatsAvailable: 32,
    ),
    Program(
      id: 'p18',
      title: 'Investor Intelligence Seminar',
      category: 'Seminar',
      description: 'Learn investor expectations, due diligence, and pitch feedback.',
      date: DateTime.now().add(const Duration(days: 22)),
      location: 'Finance Lab',
      seatsAvailable: 26,
    ),
    Program(
      id: 'p19',
      title: 'Tech Trends Seminar',
      category: 'Seminar',
      description: 'Explore emerging tech in AI, blockchain, and the future of work.',
      date: DateTime.now().add(const Duration(days: 24)),
      location: 'Innovation Hall',
      seatsAvailable: 30,
    ),
    Program(
      id: 'p20',
      title: 'Mental Health at Work Seminar',
      category: 'Seminar',
      description: 'Practical strategies for wellness, boundaries, and burnout prevention.',
      date: DateTime.now().add(const Duration(days: 26)),
      location: 'Health Center',
      seatsAvailable: 40,
    ),
    // Workshop
    Program(
      id: 'p21',
      title: 'Intro to Flutter Workshop',
      category: 'Workshop',
      description:
          'A hands-on session covering widgets, state management, and '
          'building your first cross-platform screen.',
      date: DateTime.now().add(const Duration(days: 3)),
      location: 'Online — Zoom',
      seatsAvailable: 24,
    ),
    Program(
      id: 'p22',
      title: 'Business Model Canvas Workshop',
      category: 'Workshop',
      description: 'Prototype your startup idea and map customer value propositions.',
      date: DateTime.now().add(const Duration(days: 6)),
      location: 'Design Studio',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p23',
      title: 'App Development Workshop',
      category: 'Workshop',
      description: 'Build a mobile app prototype using modern development tools.',
      date: DateTime.now().add(const Duration(days: 9)),
      location: 'Coding Studio — Room 4',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p24',
      title: 'Finance Spreadsheet Workshop',
      category: 'Workshop',
      description: 'Use spreadsheets to analyze budgets, forecasts, and KPIs.',
      date: DateTime.now().add(const Duration(days: 11)),
      location: 'Finance Lab',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p25',
      title: 'Startup Pitch Workshop',
      category: 'Workshop',
      description: 'Craft a compelling pitch and practice presenting to investors.',
      date: DateTime.now().add(const Duration(days: 13)),
      location: 'Pitch Room',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p26',
      title: 'Customer Research Workshop',
      category: 'Workshop',
      description: 'Learn interview methods, personas, and customer pain mapping.',
      date: DateTime.now().add(const Duration(days: 15)),
      location: 'Market Studio',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p27',
      title: 'UX Design Workshop',
      category: 'Workshop',
      description: 'Create user flows, wireframes, and testing plans for digital products.',
      date: DateTime.now().add(const Duration(days: 17)),
      location: 'Design Studio',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p28',
      title: 'Growth Marketing Workshop',
      category: 'Workshop',
      description: 'Experiment with funnels, ads, content, and analytics.',
      date: DateTime.now().add(const Duration(days: 19)),
      location: 'Marketing Lab',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p29',
      title: 'Leadership Skills Workshop',
      category: 'Workshop',
      description: 'Practice feedback, delegation, and psychological safety in teams.',
      date: DateTime.now().add(const Duration(days: 21)),
      location: 'Excelerate Hub — Room 109',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p30',
      title: 'Sales Strategy Workshop',
      category: 'Workshop',
      description: 'Build a sales process, qualifying questions, and pipeline metrics.',
      date: DateTime.now().add(const Duration(days: 23)),
      location: 'Business Center',
      seatsAvailable: 20,
    ),
    // Masterclass
    Program(
      id: 'p31',
      title: 'Digital Marketing Masterclass',
      category: 'Masterclass',
      description: 'Learn campaign planning, analytics, and storytelling for modern teams.',
      date: DateTime.now().add(const Duration(days: 18)),
      location: 'Online — Zoom',
      seatsAvailable: 30,
    ),
    Program(
      id: 'p32',
      title: 'Advanced App Development Masterclass',
      category: 'Masterclass',
      description: 'Build scalable app architectures and deployment workflows.',
      date: DateTime.now().add(const Duration(days: 20)),
      location: 'Coding Studio — Room 2',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p33',
      title: 'Financial Modeling Masterclass',
      category: 'Masterclass',
      description: 'Build investment models, scenario plans, and revenue forecasts.',
      date: DateTime.now().add(const Duration(days: 22)),
      location: 'Finance Lab',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p34',
      title: 'Business Strategy Masterclass',
      category: 'Masterclass',
      description: 'Learn competitive analysis, growth planning, and execution frameworks.',
      date: DateTime.now().add(const Duration(days: 24)),
      location: 'Business Center',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p35',
      title: 'AI Product Masterclass',
      category: 'Masterclass',
      description: 'Discover how to design, launch, and manage AI product offerings.',
      date: DateTime.now().add(const Duration(days: 26)),
      location: 'Innovation Hall',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p36',
      title: 'Data Science Masterclass',
      category: 'Masterclass',
      description: 'Advance your analytics skills with modeling, visualization, and deployment.',
      date: DateTime.now().add(const Duration(days: 28)),
      location: 'Data Lab — Room 1',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p37',
      title: 'Sales Leadership Masterclass',
      category: 'Masterclass',
      description: 'Lead high-performance sales teams and design incentive plans.',
      date: DateTime.now().add(const Duration(days: 30)),
      location: 'Executive Suite',
      seatsAvailable: 15,
    ),
    Program(
      id: 'p38',
      title: 'Startup Growth Masterclass',
      category: 'Masterclass',
      description: 'Learn scaling, retention, and growth frameworks for early-stage startups.',
      date: DateTime.now().add(const Duration(days: 32)),
      location: 'Startup Studio',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p39',
      title: 'Blockchain Business Masterclass',
      category: 'Masterclass',
      description: 'Explore blockchain strategy, token models, and digital ecosystems.',
      date: DateTime.now().add(const Duration(days: 34)),
      location: 'Innovation Hall',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p40',
      title: 'User Experience Masterclass',
      category: 'Masterclass',
      description: 'Master UX research, design systems, and accessibility best practices.',
      date: DateTime.now().add(const Duration(days: 36)),
      location: 'Design Studio',
      seatsAvailable: 18,
    ),
    // Intensive
    Program(
      id: 'p41',
      title: 'Interview Prep Intensive',
      category: 'Intensive',
      description: 'Practice technical and behavioral interviews with expert coaches.',
      date: DateTime.now().add(const Duration(days: 25)),
      location: 'Career Center',
      seatsAvailable: 8,
    ),
    Program(
      id: 'p42',
      title: 'Startup Launch Intensive',
      category: 'Intensive',
      description: 'Go from idea to launch plan in an immersive intensive experience.',
      date: DateTime.now().add(const Duration(days: 29)),
      location: 'Startup Studio',
      seatsAvailable: 12,
    ),
    Program(
      id: 'p43',
      title: 'Advanced Coding Intensive',
      category: 'Intensive',
      description: 'Deep dive into software engineering best practices and architecture.',
      date: DateTime.now().add(const Duration(days: 31)),
      location: 'Coding Studio — Room 1',
      seatsAvailable: 14,
    ),
    Program(
      id: 'p44',
      title: 'Finance Analytics Intensive',
      category: 'Intensive',
      description: 'Advanced financial analysis with modeling, reports, and dashboards.',
      date: DateTime.now().add(const Duration(days: 33)),
      location: 'Finance Lab',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p45',
      title: 'Leadership Intensive',
      category: 'Intensive',
      description: 'Hands-on leadership coaching for managers and founders.',
      date: DateTime.now().add(const Duration(days: 35)),
      location: 'Executive Suite',
      seatsAvailable: 10,
    ),
    Program(
      id: 'p46',
      title: 'E-commerce Intensive',
      category: 'Intensive',
      description: 'Build and optimize an online store using real-world tools.',
      date: DateTime.now().add(const Duration(days: 37)),
      location: 'Business Center',
      seatsAvailable: 15,
    ),
    Program(
      id: 'p47',
      title: 'Data Engineering Intensive',
      category: 'Intensive',
      description: 'Design pipelines, ETL processes, and data warehouse workflows.',
      date: DateTime.now().add(const Duration(days: 39)),
      location: 'Data Lab — Room 3',
      seatsAvailable: 12,
    ),
    Program(
      id: 'p48',
      title: 'Brand Strategy Intensive',
      category: 'Intensive',
      description: 'Create brand positioning, messaging, and launch plans.',
      date: DateTime.now().add(const Duration(days: 41)),
      location: 'Marketing Lab',
      seatsAvailable: 15,
    ),
    Program(
      id: 'p49',
      title: 'Customer Success Intensive',
      category: 'Intensive',
      description: 'Build onboarding, retention, and customer success playbooks.',
      date: DateTime.now().add(const Duration(days: 43)),
      location: 'Business Center',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p50',
      title: 'Creative Leadership Intensive',
      category: 'Intensive',
      description: 'Lead creative teams, portfolio reviews, and project delivery.',
      date: DateTime.now().add(const Duration(days: 45)),
      location: 'Design Studio',
      seatsAvailable: 14,
    ),
    // Finance
    Program(
      id: 'p51',
      title: 'Financial Modeling Workshop',
      category: 'Finance',
      description: 'Build financial projections, revenue models, and investor-ready reports.',
      date: DateTime.now().add(const Duration(days: 5)),
      location: 'Finance Lab',
      seatsAvailable: 24,
    ),
    Program(
      id: 'p52',
      title: 'Investing Basics Seminar',
      category: 'Finance',
      description: 'Learn investment fundamentals, asset classes, and portfolio basics.',
      date: DateTime.now().add(const Duration(days: 8)),
      location: 'Online — Zoom',
      seatsAvailable: 30,
    ),
    Program(
      id: 'p53',
      title: 'Corporate Finance Masterclass',
      category: 'Finance',
      description: 'Understand valuation, capital structure, and financial decision-making.',
      date: DateTime.now().add(const Duration(days: 12)),
      location: 'Business Center',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p54',
      title: 'Budgeting & Forecasting Workshop',
      category: 'Finance',
      description: 'Create operating budgets, forecasts, and financial dashboards.',
      date: DateTime.now().add(const Duration(days: 16)),
      location: 'Finance Lab',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p55',
      title: 'Tax Strategy Seminar',
      category: 'Finance',
      description: 'Learn tax planning basics for individuals and small businesses.',
      date: DateTime.now().add(const Duration(days: 18)),
      location: 'Online — Teams',
      seatsAvailable: 28,
    ),
    Program(
      id: 'p56',
      title: 'Fintech Innovation Bootcamp',
      category: 'Finance',
      description: 'Explore fintech products, digital payments, and financial APIs.',
      date: DateTime.now().add(const Duration(days: 20)),
      location: 'Innovation Lab',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p57',
      title: 'Risk Management Seminar',
      category: 'Finance',
      description: 'Identify and manage financial risks in business operations.',
      date: DateTime.now().add(const Duration(days: 22)),
      location: 'Risk Room',
      seatsAvailable: 26,
    ),
    Program(
      id: 'p58',
      title: 'Personal Wealth Workshop',
      category: 'Finance',
      description: 'Plan savings, investments, and retirement with practical tools.',
      date: DateTime.now().add(const Duration(days: 24)),
      location: 'Finance Lab',
      seatsAvailable: 30,
    ),
    Program(
      id: 'p59',
      title: 'Business Valuation Seminar',
      category: 'Finance',
      description: 'Learn valuation methods for startups, small businesses, and M&A.',
      date: DateTime.now().add(const Duration(days: 26)),
      location: 'Business Center',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p60',
      title: 'Financial Leadership Masterclass',
      category: 'Finance',
      description: 'Lead finance teams, align strategy, and communicate business results.',
      date: DateTime.now().add(const Duration(days: 28)),
      location: 'Executive Suite',
      seatsAvailable: 18,
    ),
    // Business
    Program(
      id: 'p61',
      title: 'Business Growth Strategy Workshop',
      category: 'Business',
      description: 'Plan growth, scale operations, and sharpen business models.',
      date: DateTime.now().add(const Duration(days: 6)),
      location: 'Business Center',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p62',
      title: 'Entrepreneurship Bootcamp',
      category: 'Business',
      description: 'Validate ideas, pitch investors, and prepare a business plan.',
      date: DateTime.now().add(const Duration(days: 19)),
      location: 'Startup Studio',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p63',
      title: 'Sales Leadership Seminar',
      category: 'Business',
      description: 'Build sales processes, hiring plans, and revenue operations.',
      date: DateTime.now().add(const Duration(days: 17)),
      location: 'Executive Suite',
      seatsAvailable: 24,
    ),
    Program(
      id: 'p64',
      title: 'Operations Excellence Workshop',
      category: 'Business',
      description: 'Optimize workflows, quality, and team performance.',
      date: DateTime.now().add(const Duration(days: 21)),
      location: 'Operations Room',
      seatsAvailable: 26,
    ),
    Program(
      id: 'p65',
      title: 'Marketing Fundamentals Seminar',
      category: 'Business',
      description: 'Build brand positioning, messaging, and marketing plans.',
      date: DateTime.now().add(const Duration(days: 23)),
      location: 'Marketing Lab',
      seatsAvailable: 30,
    ),
    Program(
      id: 'p66',
      title: 'Business Analytics Workshop',
      category: 'Business',
      description: 'Use data to improve decision-making, sales, and customer success.',
      date: DateTime.now().add(const Duration(days: 25)),
      location: 'Data Lab',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p67',
      title: 'Leadership Essentials Seminar',
      category: 'Business',
      description: 'Strengthen leadership presence, meetings, and decision frameworks.',
      date: DateTime.now().add(const Duration(days: 27)),
      location: 'Excelerate Hub — Room 112',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p68',
      title: 'Customer Experience Workshop',
      category: 'Business',
      description: 'Map customer journeys and improve retention through service design.',
      date: DateTime.now().add(const Duration(days: 29)),
      location: 'Customer Lab',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p69',
      title: 'Business Negotiation Seminar',
      category: 'Business',
      description: 'Practice negotiation tactics, contracts, and partnerships.',
      date: DateTime.now().add(const Duration(days: 31)),
      location: 'Boardroom',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p70',
      title: 'Strategy Execution Intensive',
      category: 'Business',
      description: 'Align teams, OKRs, and execution plans for business outcomes.',
      date: DateTime.now().add(const Duration(days: 33)),
      location: 'Business Center',
      seatsAvailable: 18,
    ),
    // App Development
    Program(
      id: 'p71',
      title: 'App Development Workshop',
      category: 'App Development',
      description: 'Build a mobile app prototype using modern development tools.',
      date: DateTime.now().add(const Duration(days: 9)),
      location: 'Coding Studio — Room 4',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p72',
      title: 'React Native Bootcamp',
      category: 'App Development',
      description: 'Create cross-platform apps with React Native and reusable components.',
      date: DateTime.now().add(const Duration(days: 11)),
      location: 'Coding Studio — Room 6',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p73',
      title: 'Backend API Workshop',
      category: 'App Development',
      description: 'Build REST APIs, authentication, and database integration.',
      date: DateTime.now().add(const Duration(days: 13)),
      location: 'Tech Center — Room 5',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p74',
      title: 'UX/UI for Apps Seminar',
      category: 'App Development',
      description: 'Design app interfaces for usability, accessibility, and delight.',
      date: DateTime.now().add(const Duration(days: 15)),
      location: 'Design Studio',
      seatsAvailable: 26,
    ),
    Program(
      id: 'p75',
      title: 'Mobile Performance Optimization Seminar',
      category: 'App Development',
      description: 'Improve app speed, memory use, and battery performance.',
      date: DateTime.now().add(const Duration(days: 17)),
      location: 'Online — Zoom',
      seatsAvailable: 24,
    ),
    Program(
      id: 'p76',
      title: 'App Deployment Workshop',
      category: 'App Development',
      description: 'Publish apps to stores and manage releases.',
      date: DateTime.now().add(const Duration(days: 19)),
      location: 'Coding Studio — Room 5',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p77',
      title: 'Flutter Advanced Workshop',
      category: 'App Development',
      description: 'Build complex navigation, state management, and plugins.',
      date: DateTime.now().add(const Duration(days: 21)),
      location: 'Online — Google Meet',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p78',
      title: 'App Security Seminar',
      category: 'App Development',
      description: 'Protect applications from vulnerabilities and data leaks.',
      date: DateTime.now().add(const Duration(days: 23)),
      location: 'Security Lab',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p79',
      title: 'Cross-Platform App Masterclass',
      category: 'App Development',
      description: 'Master cross-platform frameworks and deployment tradeoffs.',
      date: DateTime.now().add(const Duration(days: 25)),
      location: 'Innovation Hall',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p80',
      title: 'App Analytics Workshop',
      category: 'App Development',
      description: 'Measure user behavior, funnels, and retention with analytics tools.',
      date: DateTime.now().add(const Duration(days: 27)),
      location: 'Data Lab',
      seatsAvailable: 22,
    ),
    // Data Science
    Program(
      id: 'p81',
      title: 'Data Analytics Info Session',
      category: 'Data Science',
      description:
          'Learn what the Data Analytics track covers and how to apply '
          'for the next cohort.',
      date: DateTime.now().add(const Duration(days: 10)),
      location: 'Online — Google Meet',
      seatsAvailable: 50,
    ),
    Program(
      id: 'p82',
      title: 'Data Science Bootcamp',
      category: 'Data Science',
      description: 'Learn analytics, machine learning, and practical data projects.',
      date: DateTime.now().add(const Duration(days: 23)),
      location: 'Data Lab — Room 2',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p83',
      title: 'Machine Learning Workshop',
      category: 'Data Science',
      description: 'Build predictive models and evaluate machine learning workflows.',
      date: DateTime.now().add(const Duration(days: 26)),
      location: 'Data Lab — Room 4',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p84',
      title: 'Data Visualization Seminar',
      category: 'Data Science',
      description: 'Turn data into dashboards and visual narratives.',
      date: DateTime.now().add(const Duration(days: 28)),
      location: 'Design Studio',
      seatsAvailable: 24,
    ),
    Program(
      id: 'p85',
      title: 'Big Data Workshop',
      category: 'Data Science',
      description: 'Work with large datasets, pipelines, and cloud storage.',
      date: DateTime.now().add(const Duration(days: 30)),
      location: 'Data Center',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p86',
      title: 'AI for Data Science Seminar',
      category: 'Data Science',
      description: 'Explore AI applications in analytics and data products.',
      date: DateTime.now().add(const Duration(days: 32)),
      location: 'Innovation Hall',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p87',
      title: 'Deep Learning Masterclass',
      category: 'Data Science',
      description: 'Delve into neural networks, computer vision, and NLP techniques.',
      date: DateTime.now().add(const Duration(days: 34)),
      location: 'Tech Center — Room 7',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p88',
      title: 'Data Ethics Seminar',
      category: 'Data Science',
      description: 'Understand ethical data collection, privacy, and algorithm fairness.',
      date: DateTime.now().add(const Duration(days: 36)),
      location: 'Meetup Hall',
      seatsAvailable: 26,
    ),
    Program(
      id: 'p89',
      title: 'Analytics Leadership Workshop',
      category: 'Data Science',
      description: 'Lead analytics teams, data culture, and impact measurement.',
      date: DateTime.now().add(const Duration(days: 38)),
      location: 'Executive Suite',
      seatsAvailable: 16,
    ),
    Program(
      id: 'p90',
      title: 'Business Intelligence Seminar',
      category: 'Data Science',
      description: 'Use BI tools to surface insights and support decision-making.',
      date: DateTime.now().add(const Duration(days: 40)),
      location: 'Business Center',
      seatsAvailable: 24,
    ),
    // Marketing
    Program(
      id: 'p91',
      title: 'Growth Marketing Workshop',
      category: 'Marketing',
      description: 'Experiment with funnels, ads, content, and analytics.',
      date: DateTime.now().add(const Duration(days: 19)),
      location: 'Marketing Lab',
      seatsAvailable: 22,
    ),
    Program(
      id: 'p92',
      title: 'Brand Strategy Intensive',
      category: 'Marketing',
      description: 'Create brand positioning, messaging, and launch plans.',
      date: DateTime.now().add(const Duration(days: 37)),
      location: 'Marketing Lab',
      seatsAvailable: 15,
    ),
    Program(
      id: 'p93',
      title: 'Social Media for Business Seminar',
      category: 'Marketing',
      description: 'Plan social campaigns for engagement and conversions.',
      date: DateTime.now().add(const Duration(days: 41)),
      location: 'Online — Zoom',
      seatsAvailable: 35,
    ),
    Program(
      id: 'p94',
      title: 'Content Marketing Masterclass',
      category: 'Marketing',
      description: 'Build content strategies for storytelling and inbound growth.',
      date: DateTime.now().add(const Duration(days: 43)),
      location: 'Design Studio',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p95',
      title: 'Customer Research Workshop',
      category: 'Marketing',
      description: 'Gather customer insights and use them to improve marketing.',
      date: DateTime.now().add(const Duration(days: 45)),
      location: 'Market Studio',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p96',
      title: 'Email Marketing Seminar',
      category: 'Marketing',
      description: 'Build campaigns, automation, and subscriber journeys.',
      date: DateTime.now().add(const Duration(days: 47)),
      location: 'Online — Teams',
      seatsAvailable: 28,
    ),
    Program(
      id: 'p97',
      title: 'Analytics-Driven Marketing Workshop',
      category: 'Marketing',
      description: 'Use metrics, A/B tests, and dashboards to optimize campaigns.',
      date: DateTime.now().add(const Duration(days: 49)),
      location: 'Data Lab',
      seatsAvailable: 18,
    ),
    Program(
      id: 'p98',
      title: 'Digital Advertising Workshop',
      category: 'Marketing',
      description: 'Run paid media campaigns across search and social channels.',
      date: DateTime.now().add(const Duration(days: 51)),
      location: 'Marketing Lab',
      seatsAvailable: 20,
    ),
    Program(
      id: 'p99',
      title: 'Influencer Marketing Seminar',
      category: 'Marketing',
      description: 'Create partnerships and campaigns with creators and influencers.',
      date: DateTime.now().add(const Duration(days: 53)),
      location: 'Online — Zoom',
      seatsAvailable: 25,
    ),
    Program(
      id: 'p100',
      title: 'Performance Marketing Masterclass',
      category: 'Marketing',
      description: 'Optimize paid acquisition, ROI, and channel performance.',
      date: DateTime.now().add(const Duration(days: 55)),
      location: 'Business Center',
      seatsAvailable: 18,
    ),
  ];

  static List<Program> getAll() => List.unmodifiable(_programs);

  static Program getById(String id) =>
      _programs.firstWhere((p) => p.id == id);

  static List<Program> getRegisteredPrograms() {
    return _programs.where((program) => AuthRepository.isProgramRegistered(program.id)).toList();
  }

  static List<Program> getCurrentlyHappeningPrograms() {
    return _programs.where((program) =>
        program.date.isBefore(DateTime.now().add(const Duration(days: 7))) &&
        AuthRepository.isProgramRegistered(program.id)).toList();
  }

  static List<Program> getUpcomingPrograms() {
    return _programs.where((program) =>
        !AuthRepository.isProgramRegistered(program.id) &&
        program.date.isAfter(DateTime.now())).toList().take(4).toList();
  }

  static Future<void> toggleRegistration(String id) async {
    await AuthRepository.toggleProgramRegistration(id);
  }
}
